version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-words-dictionary
    environment:
      MYSQL_ROOT_PASSWORD: watchoutfortherope
      MYSQL_USER: admin
      MYSQL_PASSWORD: death
      MYSQL_DATABASE: words_dictionary
    networks:
      mynetwork:
    ports:
      - "3306:3306" # enlever le numéro de port pour empêcher l'accès à la database ?
    volumes:
      - mysql-data:/var/lib/mysql
      - ./hangmandatabase.sql:/docker-entrypoint-initdb.d/hangmandatabase.sql

networks:
  mynetwork:

volumes:
  mysql-data:
