version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-words-dictionary
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./hangmandatabase.sql:/docker-entrypoint-initdb.d/hangmandatabase.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "2001:2001"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - ./backend:/app/backend  # Partager le code backend avec le frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.flask
    container_name: frontend
    ports:
      - "2323:2323"
    depends_on:
      - backend
    networks:
      - mynetwork
    volumes:
      - ./backend:/app/backend  # Partager le code backend avec le frontend

networks:
  mynetwork:

volumes:
  mysql-data: