# Utiliser une image officielle de Node.js comme base
FROM node:16

# Créer et définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et package-lock.json (si disponibles)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le reste du code source dans le conteneur
COPY . .

# Exposer le port que l'application Node.js va utiliser
EXPOSE 3000

# Commande à exécuter pour démarrer l'application
CMD ["node", "server.js"]